#!/usr/bin/env php
<?php
    ini_set("display_errors", false);
    require_once __DIR__."/bootstrap/autoload.php";
    $app = include(constant("R_APP_ROOT_DIR")."/bootstrap/app.php");
    $artisan = R\Lib\Console\ConsoleApplication::start($app);
    $status = $artisan->run();
    $app->shutdown();
    exit($status);
