<?php
	
	// Schama created from csv-file.
	registry(array(
		'Schema.tables.Member' =>array('label' =>'会員'),
		'Schema.cols.Member' =>array(
			'name' =>array('label' =>'氏名', 'def.type' =>'text', 'type' =>'text'),
			'nickname' =>array('label' =>'ニックネーム', 'def.type' =>'text', 'type' =>'text'),
			'mail' =>array('label' =>'メールアドレス', 'def.type' =>'text', 'type' =>'text', 'def.mail' =>true),
			'gender' =>array('label' =>'性別', 'def.type' =>'text', 'type' =>'radioselect'),
			'birthday' =>array('label' =>'生年月日', 'def.type' =>'datetime', 'type' =>'date'),
			'job' =>array('label' =>'職業', 'def.type' =>'text', 'type' =>'checklist'),
			'interest' =>array('label' =>'興味関心', 'def.type' =>'text', 'type' =>'checklist'),
			'login_id' =>array('label' =>'ログインID', 'def.type' =>'text', 'type' =>'text', 'def.login_id' =>true),
			'login_pw' =>array('label' =>'パスワード', 'def.type' =>'text', 'type' =>'password', 'def.login_pw' =>true),
			'mail_cred' =>array('label' =>'メールキー', 'def.type' =>'text', 'def.mail_cred' =>true),
			'mail_cred_date' =>array('label' =>'メールキー発行日時', 'def.type' =>'text', 'def.mail_cred_date' =>true),
			'id' =>array('label' =>'ID', 'def.type' =>'integer', 'def.id' =>true, 'def.autoincrement' =>true),
			'reg_date' =>array('label' =>'登録日時', 'def.type' =>'datetime', 'def.reg_date' =>true),
			'del_flg' =>array('label' =>'削除フラグ', 'def.type' =>'integer', 'def.del_flg' =>true, 'def.default' =>0),
		),
		'Schema.tables.FavolitePost' =>array('label' =>'お気に入り記事'),
		'Schema.cols.FavolitePost' =>array(
			'member_id' =>array('label' =>'会員ID', 'def.type' =>'integer'),
			'post_id' =>array('label' =>'記事ID', 'def.type' =>'integer'),
			'id' =>array('label' =>'ID', 'def.type' =>'integer', 'def.id' =>true, 'def.autoincrement' =>true),
		),
		'Schema.tables.Post' =>array('label' =>'記事'),
		'Schema.cols.Post' =>array(
			'title' =>array('label' =>'タイトル', 'def.type' =>'text', 'type' =>'text'),
			'content' =>array('label' =>'本文', 'def.type' =>'text', 'type' =>'textarea'),
			'youtube_id' =>array('label' =>'youtubeID', 'def.type' =>'text', 'type' =>'text'),
			'discovery_rank' =>array('label' =>'DISCOVERY枠順位', 'def.type' =>'integer', 'type' =>'text'),
			'keyword' =>array('label' =>'META KEYWORD', 'def.type' =>'text', 'type' =>'text'),
			'description' =>array('label' =>'META DESCRIPTION', 'def.type' =>'text', 'type' =>'text'),
			'category' =>array('label' =>'カテゴリー', 'def.type' =>'text', 'type' =>'select'),
			'thumbnail_img' =>array('label' =>'サムネイル画像', 'def.type' =>'text', 'type' =>'file', 'storage' =>'public'),
			'display_date' =>array('label' =>'掲載日付', 'def.type' =>'datetime', 'type' =>'date'),
			'display_end_date' =>array('label' =>'掲載終了日付', 'def.type' =>'datetime', 'type' =>'date'),
			'draft_flg' =>array('label' =>'下書きフラグ', 'def.type' =>'integer'),
			'pv_count' =>array('label' =>'閲覧数', 'def.type' =>'integer'),
			'id' =>array('label' =>'ID', 'def.type' =>'integer', 'def.id' =>true, 'def.autoincrement' =>true),
			'reg_date' =>array('label' =>'登録日時', 'def.type' =>'datetime', 'def.reg_date' =>true),
			'del_flg' =>array('label' =>'削除フラグ', 'def.type' =>'integer', 'def.del_flg' =>true, 'def.default' =>0),
		),
		'Schema.tables.Contact' =>array('label' =>'お問い合わせ', 'nodef' =>true),
		'Schema.cols.Contact' =>array(
			'category' =>array('label' =>'問い合わせ種別', 'type' =>'radioselect'),
			'content' =>array('label' =>'本文', 'type' =>'textarea'),
			'name' =>array('label' =>'氏名', 'type' =>'text'),
			'mail' =>array('label' =>'メールアドレス', 'type' =>'text'),
		),
		'Schema.controller' =>array(
			'index' =>array('type' =>'index', 'label' =>'トップページ', 'accessor' =>'member'),
			'posts' =>array(
				'type' =>'master',
				'label' =>'記事表示',
				'table' =>'Post',
				'accessor' =>'member',
				'usage' =>'view',
			),
			'contact' =>array(
				'type' =>'master',
				'label' =>'問い合わせフォーム',
				'table' =>'Contact',
				'accessor' =>'member',
				'usage' =>'form',
			),
			'member_register' =>array(
				'type' =>'master',
				'label' =>'会員登録',
				'table' =>'Member',
				'accessor' =>'member',
				'usage' =>'form',
			),
			'member_login' =>array('type' =>'login', 'label' =>'会員ログイン', 'table' =>'Member', 'accessor' =>'member'),
			'member_index' =>array('type' =>'index', 'label' =>'会員トップ', 'accessor' =>'member', 'auth' =>'member'),
			'member_edit' =>array(
				'type' =>'master',
				'label' =>'会員情報変更',
				'table' =>'Member',
				'accessor' =>'member',
				'auth' =>'member',
				'usage' =>'form',
			),
			'member_favolite_posts' =>array(
				'type' =>'master',
				'label' =>'お気に入り変更',
				'table' =>'Member',
				'accessor' =>'member',
				'auth' =>'member',
				'usage' =>'form',
			),
			'admin_login' =>array('type' =>'login', 'label' =>'管理者ログイン', 'accessor' =>'admin'),
			'admin_index' =>array('type' =>'index', 'label' =>'管理者トップ', 'accessor' =>'admin', 'auth' =>'admin'),
			'admin_post_master' =>array(
				'type' =>'master',
				'label' =>'記事管理',
				'table' =>'Post',
				'accessor' =>'admin',
				'auth' =>'admin',
				'use_csv' =>1,
			),
			'admin_member_master' =>array(
				'type' =>'master',
				'label' =>'会員管理',
				'table' =>'Member',
				'accessor' =>'admin',
				'auth' =>'admin',
				'use_csv' =>1,
			),
		),
	));
	